Repository atlp-rwanda/cod-be, pull requests merged in 2022-03, with the labels that each got.

#1 #181414542 Setup Boilerplate
  .babelrc
  .env.example
  nodemon.json
  package-lock.json
  package.json
  src/app.js
  src/config/index.js
  src/controllers/index.js
  src/database/index.js
  src/exceptions/index.js
  src/index.js
  src/middlewares/index.js
  src/routes/index.js
  src/services/index.js
  src/validations/index.js
  yarn.lock
Labels: Ready

#16 #181414543 Configure BN Postgres Database & Sequelize ORM
  .DS_Store
  .babelrc
  .dockerignore
  .env.example
  .eslint.json
  .eslintrc.json
  .gitignore
  .hound.yml
  .sequelizerc
  Dockerfile
  README.md
  build/index.js
  docker-compose.yml
  nodemon.json
  package-lock.json
  package.json
  public/api-docs/swagger.js
  src/app.js
  src/config/index.js
  src/database/config/config.js
  src/database/migrations/20220307124806-create-offices.js
  src/database/models/index.js
  src/database/models/offices.js
  src/database/seeders/20220304143123-demo-offices.js
  src/index.js
  src/routes/index.js
  src/routes/offices.js
  yarn.lock
Labels: Ready

#19 #181414596 Setup Swagger Documentation
  .DS_Store
  .env.example
  .gitignore
  README.md
  build/index.js
  nodemon.json
  public/.DS_Store
  public/api-docs/.DS_Store
  public/api-docs/swagger.js
  public/api-docs/users.yaml
  src/app.js
  src/database/migrations/20220307124806-create-users.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-offices.js
  src/database/seeders/20220304143123-demo-users.js
  src/index.js
  src/routes/offices.js
  src/routes/users.js
Labels: Ready

#20 #181414543 Configure BN Postgres Database & Sequelize ORM
  .DS_Store
  .env.example
  .gitignore
  build/index.js
  nodemon.json
  public/.DS_Store
  public/api-docs/.DS_Store
  public/api-docs/swagger.js
  public/api-docs/users.yaml
  src/app.js
  src/database/migrations/20220307124806-create-users.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-offices.js
  src/database/seeders/20220304143123-demo-users.js
  src/index.js
  src/routes/offices.js
  src/routes/users.js
Labels: Changes requested

#25 #181414544-Ch-Setup-Unit-Testing
  .eslint.json
  .eslintrc.json
  package-lock.json
  package.json
  test/index.spec.js
Labels: Ready

#31 #181414596 Fix Swagger Documentation
  .DS_Store
  .babelrc
  .env.example
  .eslint.json
  .prettierrc.json
  nodemon.json
  package-lock.json
  package.json
  public/api-docs/index.yaml
  public/api-docs/users.yaml
  src/app.js
  src/config/index.js
  src/database/config/config.js
  src/database/migrations/20220307124806-create-users.js
  src/database/models/index.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-users.js
  src/index.js
  src/routes/index.js
  src/routes/users.js
  src/services/index.js
  src/validations/index.js
  yarn.lock
Labels: Ready

#22 #181414545 Fix: configure ESLint
  .eslint.json
  .eslintrc.json
  .prettierrc.json
  package.json
Labels: Ready

#33 #181414543 Fix PostgresDB Setup
  package-lock.json
  package.json
  src/routes/index.js
Labels: Under Review

#37 Fix-/Deploy-App-on-Heroku
  Procfile
Labels: Ready

#30 Ch integrate coveralls code coverage service #181414547
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  test/index.spec.js
Labels: Ready

#42 Fix package and yarn lock files error on heroku
  .gitignore
  yarn.lock
Labels: Ready

#43 #181414599 Ft-User Registration with JWT
  .env.example
  .gitignore
  README.md
  nodemon.json
  package-lock.json
  package.json
  public/api-docs/users.yaml
  src/app.js
  src/config/envConfig.js
  src/config/index.js
  src/controllers/index.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20220307124806-create-users.js
  src/database/models/index.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-users.js
  src/index.js
  src/routes/index.js
  src/routes/users.js
  src/services/userService.js
  src/utils/errors/alreadyExistError.js
  src/utils/errors/applicationsErrors.js
  src/utils/helpers/generateToken.js
  src/validations/envValidation.js
  src/validations/index.js
  src/validations/userValidation.js
  test/user.spec.js
Labels: Ready

#34 Ch log in bn email password #181414603
  .env.example
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  public/api-docs/users.yaml
  src/app.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20220321064904-create-logged-in-user.js
  src/database/models/loggedinuser.js
  src/database/models/users.js
  src/middlewares/authenticate.js
  src/routes/users.js
  src/services/storeToken.js
  src/services/userService.js
  src/utils/helpers/generateToken.js
  test/login.test.js
  test/refreshToken.test.js
  yarn.lock
Labels: Under Review

#46 #181414600 Feature User Email Verification
  .env.example
  .eslintignore
  .github/workflows/node.js.yml
  README.md
  nodemon.json
  package-lock.json
  package.json
  public/.DS_Store
  public/api-docs/.DS_Store
  public/api-docs/swagger.js
  public/api-docs/users.yaml
  src/app.js
  src/config/envConfig.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20220316160418-modify_users_add_email_token.js
  src/database/migrations/20220321064904-create-logged-in-user.js
  src/database/models/loggedinuser.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-users.js
  src/index.js
  src/middlewares/authenticate.js
  src/middlewares/isVerified.js
  src/routes/users.js
  src/services/storeToken.js
  src/services/templates/sendVerification.js
  src/services/userService.js
  src/services/userVerfication.js
  src/utils/errors/applicationsErrors.js
  src/utils/helpers/generateToken.js
  test/index.spec.js
  test/login.test.js
  test/refreshToken.test.js
  test/user.spec.js
  test/userVerification.spec.js
  yarn.lock
Labels: Under Review

#50 fixing authenticate error
  README.md
  package.json
  public/api-docs/users.yaml
  src/config/envConfig.js
  src/controllers/userController.js
  src/database/migrations/20220321064904-create-logged-in-user.js
  src/database/models/loggedinuser.js
  src/routes/users.js
  src/services/storeToken.js
  src/services/userService.js
  src/utils/helpers/generateToken.js
  test/login.test.js
  test/refreshToken.test.js
Labels: Ready

#44 Feature: user roles settings #181339527
  .github/workflows/node.js.yml
  README.md
  package-lock.json
  package.json
  public/api-docs/userRoles.yaml
  src/config/envConfig.js
  src/config/index.js
  src/controllers/roleController.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20220307124806-create-users.js
  src/database/migrations/20220312053625-create-role.js
  src/database/migrations/20220316160418-modify_users_add_email_token.js
  src/database/migrations/20220321064904-create-logged-in-user.js
  src/database/models/loggedinuser.js
  src/database/models/role.js
  src/database/models/users.js
  src/database/seeders/20220304143123-demo-users.js
  src/database/seeders/20220321125534-super-admin.js
  src/index.js
  src/middlewares/authorize.js
  src/middlewares/isVerified.js
  src/routes/index.js
  src/routes/rolesRouter.js
  src/routes/users.js
  src/services/rolesService.js
  src/services/storeToken.js
  src/services/templates/sendVerification.js
  src/services/userService.js
  src/services/userVerfication.js
  src/utils/errors/alreadyExistError.js
  src/utils/errors/applicationsErrors.js
  src/utils/errors/authorizationError.js
  src/utils/errors/notFoundError.js
  src/utils/helpers/generateToken.js
  src/validations/envValidation.js
  src/validations/index.js
  src/validations/roleValidation.js
  src/validations/userValidation.js
  test/index.spec.js
  test/login.test.js
  test/refreshToken.test.js
  test/role.spec.js
  test/user.spec.js
  test/userVerification.spec.js
Labels: Ready

#36 Ch logout functionality 181414605
  README.md
  public/api-docs/users.yaml
  src/controllers/userController.js
  src/middlewares/authenticate.js
  src/routes/users.js
  src/utils/errors/applicationsErrors.js
  test/logout.test.js
Labels: Ready

#32 #181414604 Login via Google and Facebook
  .env.example
  .github/workflows/node.js.yml
  .hound.yml
  package-lock.json
  package.json
  src/config/envConfig.js
  src/controllers/socialOauth.controller.js
  src/database/migrations/20220314141526-create-social-user.js
  src/database/models/users.js
  src/routes/index.js
  src/routes/socialOauth.route.js
  src/services/templates/social.html
  test/socialAuth.spec.js
Labels: Ready
